import {
  UserProfile,
  SpreeItem,
  OpenChallenge,
  OpenRankingItem,
  BrandCampaign,
  ProductItem,
  CommunityPass,
  OrderRecord,
  KPIMetric,
  TrendDataPoint,
  TopPerformingItem,
  WalletSummary,
  StoryHighlightItem,
} from '../types';

export const mockStoryCollections: StoryHighlightItem[] = [
  {
    id: 'h1',
    title: 'Highlights',
    cover_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=150',
    stories: [
      {
        id: 's1_1',
        media_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
        type: 'image' as const,
        caption: 'Golden sunsets by the coast 🌅',
        timestamp: '3h ago',
        location: 'Goa Beaches',
      },
      {
        id: 's1_2',
        media_url: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800',
        type: 'image' as const,
        caption: 'Endless horizon and pure ocean breeze 🌊',
        timestamp: '5h ago',
        location: 'Maldives',
      },
    ],
  },
  {
    id: 'h2',
    title: 'Travel',
    cover_url: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=150',
    stories: [
      {
        id: 's2_1',
        media_url: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800',
        type: 'image' as const,
        caption: 'Road tripping across mountain valleys 🏔️',
        timestamp: '1d ago',
        location: 'Ladakh Pass',
      },
      {
        id: 's2_2',
        media_url: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800',
        type: 'image' as const,
        caption: 'Whitewashed rooftops of Oia, Santorini ✨',
        timestamp: '2d ago',
        location: 'Santorini, Greece',
      },
    ],
  },
  {
    id: 'h3',
    title: 'Food',
    cover_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=150',
    stories: [
      {
        id: 's3_1',
        media_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
        type: 'image' as const,
        caption: 'Chef special gourmet tasting menu 🍷',
        timestamp: '2d ago',
        location: 'Fire & Spice Bistro',
      },
      {
        id: 's3_2',
        media_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800',
        type: 'image' as const,
        caption: 'Crispy sizzling paneer tikka with mint chutney 🧀',
        timestamp: '3d ago',
        location: 'Old Delhi Chaat',
      },
    ],
  },
  {
    id: 'h4',
    title: 'Lifestyle',
    cover_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    stories: [
      {
        id: 's4_1',
        media_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800',
        type: 'image' as const,
        caption: 'Morning coffee & creative studio flow ☕',
        timestamp: '4d ago',
        location: 'Creator Lab',
      },
    ],
  },
  {
    id: 'h5',
    title: 'Q&A',
    cover_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    stories: [
      {
        id: 's5_1',
        media_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800',
        type: 'image' as const,
        caption: 'Answer: How do I shoot steady videos? Gimbal + 60fps! 🎥',
        timestamp: '5d ago',
        location: 'Ask Me Anything',
      },
    ],
  },
];

export const mockCurrentUser: UserProfile = {
  id: 'usr_travelwithme_001',
  username: 'TravelWithMe',
  handle: '@travelwithme',
  display_name: 'Travel With Me',
  bio: 'Explorer | Storyteller | Dreamer • Turn your moments into stories ✨',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  is_verified: true,
  location: 'Bangalore, India',
  post_count: 248,
  follower_count: 12400,
  following_count: 432,
  story_highlights: mockStoryCollections,
};

export const mockSprees: SpreeItem[] = [
  {
    id: 'spree_001',
    creator_id: 'usr_travelwithme_001',
    creator: mockCurrentUser,
    title: 'Sunset vibes in Santorini',
    caption: 'Sunset vibes in Santorini 🌅 Grateful for moments like this... #travel #sunset #greece',
    media_url: 'https://assets.mixkit.co/videos/preview/mixkit-waves-in-the-water-1164-large.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=600&auto=format&fit=crop&q=80',
    type: 'VIDEO_SHORT',
    duration_seconds: 15,
    audio_title: 'Golden Hour',
    audio_artist: 'JVKE',
    claps_count: 12400,
    comments_count: 342,
    shares_count: 1200,
    saves_count: 892,
    views_count: 124800,
    has_clapped: false,
    has_saved: false,
    sponsored: {
      brand_name: 'SkyWings',
      tagline: 'Your next adventure awaits',
      cta_text: 'Explore More',
      cta_link: 'https://skywings.example.com',
      logo_url: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=60&auto=format&fit=crop&q=80',
    },
    tags: ['travel', 'sunset', 'greece'],
    created_at: '2026-10-01T12:00:00Z',
  },
  {
    id: 'spree_002',
    creator_id: 'usr_foodie_riya_002',
    creator: {
      id: 'usr_foodie_riya_002',
      username: 'FoodieRiya',
      handle: '@foodie_riya',
      display_name: 'Riya Chef',
      avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      is_verified: true,
      follower_count: 89000,
      following_count: 210,
      post_count: 154,
    },
    title: 'Sizzling Paneer Tikka Platter',
    caption: 'Sizzling Paneer Tikka Platter 🧀 Perfect weekend snack with secret spiced chutney! #foodie #paneer #streetfood',
    media_url: 'https://assets.mixkit.co/videos/preview/mixkit-hands-holding-a-bowl-of-soup-43343-large.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=600&auto=format&fit=crop&q=80',
    type: 'VIDEO_SHORT',
    duration_seconds: 22,
    audio_title: 'Desi Kitchen Beats',
    audio_artist: 'Acoustic Flavors',
    claps_count: 8920,
    comments_count: 215,
    shares_count: 840,
    saves_count: 630,
    views_count: 72300,
    has_clapped: false,
    has_saved: false,
    tags: ['food', 'paneer', 'cooking', 'streetfood'],
    created_at: '2026-10-02T14:30:00Z',
  },
  {
    id: 'spree_003',
    creator_id: 'usr_stylediaries_003',
    creator: {
      id: 'usr_stylediaries_003',
      username: 'StyleDiaries',
      handle: '@style_diaries',
      display_name: 'Aanya Style',
      avatar_url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
      is_verified: true,
      follower_count: 45200,
      following_count: 312,
      post_count: 98,
    },
    title: 'Monochrome Autumn Streetwear Inspo',
    caption: 'Monochrome Autumn Streetwear Inspo 🍂 Minimalist layered looks for rainy evenings.',
    media_url: 'https://assets.mixkit.co/videos/preview/mixkit-girl-walking-along-a-street-in-autumn-41310-large.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&auto=format&fit=crop&q=80',
    type: 'VIDEO_SHORT',
    duration_seconds: 18,
    audio_title: 'Lo-Fi Runway',
    audio_artist: 'Urban Chill',
    claps_count: 15120,
    comments_count: 420,
    shares_count: 1840,
    saves_count: 1420,
    views_count: 98400,
    has_clapped: false,
    has_saved: false,
    tags: ['fashion', 'streetwear', 'ootd'],
    created_at: '2026-10-03T18:00:00Z',
  },
];

export const mockExploreItems: SpreeItem[] = [
  ...mockSprees,
  {
    id: 'spree_004',
    creator_id: 'usr_fitwitharjun_004',
    creator: {
      id: 'usr_fitwitharjun_004',
      username: 'FitWithArjun',
      handle: '@fitwitharjun',
      display_name: 'Arjun Fitness',
      avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      is_verified: true,
      follower_count: 67000,
      following_count: 120,
      post_count: 310,
    },
    title: 'Dance always heals',
    caption: 'High energy morning cardio flow! Keep moving!',
    media_url: 'https://assets.mixkit.co/videos/preview/mixkit-young-man-training-with-a-jump-rope-42777-large.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&auto=format&fit=crop&q=80',
    type: 'VIDEO_SHORT',
    duration_seconds: 25,
    claps_count: 5800,
    comments_count: 180,
    shares_count: 730,
    saves_count: 520,
    views_count: 58200,
    tags: ['fitness', 'dance', 'wellness'],
    created_at: '2026-10-04T08:00:00Z',
  },
  {
    id: 'spree_005',
    creator_id: 'usr_techguru_005',
    creator: {
      id: 'usr_techguru_005',
      username: 'TechGuru',
      handle: '@techguru',
      display_name: 'Karan Tech',
      avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      is_verified: false,
      follower_count: 28400,
      following_count: 450,
      post_count: 82,
    },
    title: 'City lights & Night Photography',
    caption: 'Cyberpunk Tokyo aesthetics captured on 35mm prime lens.',
    media_url: 'https://assets.mixkit.co/videos/preview/mixkit-night-city-traffic-timelapse-42407-large.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    type: 'PHOTO',
    duration_seconds: 0,
    claps_count: 2100,
    comments_count: 88,
    shares_count: 310,
    saves_count: 410,
    views_count: 21000,
    tags: ['photography', 'tech', 'citylights'],
    created_at: '2026-10-05T20:00:00Z',
  },
  {
    id: 'spree_006',
    creator_id: 'usr_artisticsoul_006',
    creator: {
      id: 'usr_artisticsoul_006',
      username: 'ArtisticSoul',
      handle: '@artistic_soul',
      display_name: 'Maya Crafts',
      avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      is_verified: false,
      follower_count: 14200,
      following_count: 190,
      post_count: 67,
    },
    title: 'Ceramic pottery art in motion',
    caption: 'Clay wheel shaping with calming ambient sounds.',
    media_url: 'https://assets.mixkit.co/videos/preview/mixkit-hands-of-a-potter-shaping-a-clay-pot-42845-large.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&auto=format&fit=crop&q=80',
    type: 'LONG_VIDEO',
    duration_seconds: 140,
    claps_count: 4200,
    comments_count: 130,
    shares_count: 512,
    saves_count: 780,
    views_count: 42000,
    tags: ['art', 'pottery', 'crafts'],
    created_at: '2026-10-05T22:30:00Z',
  },
];

export const mockOpens: OpenChallenge[] = [
  {
    id: 'open_nike_001',
    creator_id: 'usr_nike_official',
    type: 'CHALLENGE',
    title: 'Move Better Challenge',
    description: 'Push your daily limits and show your high-performance movements. Win from the $50,000 global community pool.',
    cover_image_url: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800&auto=format&fit=crop&q=80',
    rules: [
      'Record a 15–45 second continuous workout or athletic routine.',
      'Show authentic effort and tag #MoveBetterChallenge.',
      'Community claps and form quality count towards score.',
    ],
    start_at: '2026-10-01T00:00:00Z',
    end_at: '2026-10-15T23:59:59Z',
    status: 'ACTIVE',
    reward_info: '$50,000 Global Reward Pool',
    max_participants: 50000,
    scoring_config: { claps: 2.0, views: 1.0, shares: 3.0, completion: 5.0 },
    participants_count: 14820,
    submissions_count: 4890,
    is_active: true,
    created_at: '2026-10-01T00:00:00Z',
    updated_at: '2026-10-01T00:00:00Z',
    badge_label: 'Sponsored by Nike',
    days_left: 5,
    mode: 'challenges',
    category: 'Fitness',
    reward_pool_amount: 50000,
    reward_pool_currency: 'USD',
    sponsor_name: 'Nike',
    creator: {
      id: 'usr_nike_official',
      username: 'Nike',
      handle: '@nike',
      display_name: 'Nike Official',
      avatar_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=150&auto=format&fit=crop&q=80',
      is_verified: true,
      follower_count: 5200000,
      following_count: 12,
      post_count: 840,
    },
  },
  {
    id: 'open_travel_002',
    creator_id: mockCurrentUser.id,
    type: 'CHALLENGE',
    title: 'Travel Tales',
    description: 'Show us your best travel moment! Capture breathtaking vistas, road trips, and cultural wonders.',
    cover_image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
    rules: [
      'Capture an authentic travel moment.',
      'Tag #TravelTales and attribute your destination.',
      'Video length 15-60 seconds in vertical 9:16 format.',
    ],
    start_at: '2026-10-01T00:00:00Z',
    end_at: '2026-10-12T23:59:59Z',
    status: 'ACTIVE',
    reward_info: '₹50,000 Reward Pool',
    max_participants: 10000,
    scoring_config: { claps: 2.0, views: 1.0, shares: 3.0, completion: 5.0 },
    participants_count: 3200,
    submissions_count: 1240,
    is_active: true,
    created_at: '2026-10-01T00:00:00Z',
    updated_at: '2026-10-01T00:00:00Z',
    badge_label: 'Sponsored',
    days_left: 5,
    mode: 'challenges',
    category: 'Travel',
    reward_pool_amount: 50000,
    creator: mockCurrentUser,
  },
  {
    id: 'open_foodie_003',
    creator_id: mockSprees[1].creator.id,
    type: 'CHALLENGE',
    title: 'Foodie Creations',
    description: 'Create your best homemade dish! Share recipes, sizzling pans, and creative garnishes.',
    cover_image_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop&q=80',
    rules: [
      'Prepare a unique dish from scratch.',
      'Mention all ingredients in the caption.',
    ],
    start_at: '2026-10-01T00:00:00Z',
    end_at: '2026-10-15T23:59:59Z',
    status: 'ACTIVE',
    reward_info: '₹25,000 Creator Reward',
    max_participants: 5000,
    scoring_config: { claps: 2.0, views: 1.0, shares: 3.0, completion: 5.0 },
    participants_count: 1800,
    submissions_count: 850,
    is_active: true,
    created_at: '2026-10-01T00:00:00Z',
    updated_at: '2026-10-01T00:00:00Z',
    badge_label: 'Creator Reward',
    days_left: 8,
    mode: 'challenges',
    category: 'Food',
    reward_pool_amount: 25000,
    creator: mockSprees[1].creator,
  },
  {
    id: 'open_style_004',
    creator_id: mockSprees[2].creator.id,
    type: 'COMPETITION',
    title: 'Style Icon',
    description: 'Show your unique fashion style! Transform thrifted outfits into runway-ready aesthetics.',
    cover_image_url: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&auto=format&fit=crop&q=80',
    rules: [
      'Present at least 2 distinct outfit transitions.',
      'High-definition vertical video.',
    ],
    start_at: '2026-10-01T00:00:00Z',
    end_at: '2026-10-18T23:59:59Z',
    status: 'ACTIVE',
    reward_info: '₹40,000 Brand Sponsored Pool',
    max_participants: 8000,
    scoring_config: { claps: 2.0, views: 1.0, shares: 3.0, completion: 5.0 },
    participants_count: 2100,
    submissions_count: 920,
    is_active: true,
    created_at: '2026-10-01T00:00:00Z',
    updated_at: '2026-10-01T00:00:00Z',
    badge_label: 'Brand Sponsored',
    days_left: 10,
    mode: 'competitions',
    category: 'Style',
    reward_pool_amount: 40000,
    creator: mockSprees[2].creator,
  },
];

export const mockLeaderboard: OpenRankingItem[] = [
  {
    rank: 1,
    score: 12400,
    submission_id: 'sub_001',
    spree_id: 'spree_001',
    user_id: 'usr_rank_1',
    creator_id: 'usr_rank_1',
    creator: {
      id: 'usr_rank_1',
      username: 'wanderwithsoul',
      full_name: 'Wander With Soul',
      avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    },
    spree_title: 'Golden Santorini Sunset',
    username: 'Wander With Soul',
    handle: '@wanderwithsoul',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    spree_thumbnail: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=300&auto=format&fit=crop&q=80',
    metrics: {
      views_count: 14200,
      completed_views_count: 11000,
      watch_completion_rate: 0.77,
      claps_count: 3200,
      comments_count: 240,
      saves_count: 580,
      shares_count: 420,
    },
    created_at: '2026-10-02T10:00:00Z',
  },
  {
    rank: 2,
    score: 10800,
    submission_id: 'sub_002',
    spree_id: 'spree_002',
    user_id: 'usr_foodie_riya_002',
    creator_id: 'usr_foodie_riya_002',
    creator: {
      id: 'usr_foodie_riya_002',
      username: 'foodie_riya',
      full_name: 'Riya Chef',
      avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    },
    spree_title: 'Sizzling Truffle Pasta',
    username: 'Riya Chef',
    handle: '@foodie_riya',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    spree_thumbnail: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=300&auto=format&fit=crop&q=80',
    metrics: {
      views_count: 11500,
      completed_views_count: 8500,
      watch_completion_rate: 0.74,
      claps_count: 2600,
      comments_count: 190,
      saves_count: 430,
      shares_count: 310,
    },
    created_at: '2026-10-02T11:00:00Z',
  },
  {
    rank: 3,
    score: 9600,
    submission_id: 'sub_003',
    spree_id: 'spree_003',
    user_id: 'usr_stylediaries_003',
    creator_id: 'usr_stylediaries_003',
    creator: {
      id: 'usr_stylediaries_003',
      username: 'style_diaries',
      full_name: 'Aanya Style',
      avatar_url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    },
    spree_title: 'Vintage Thrift Flip',
    username: 'Aanya Style',
    handle: '@style_diaries',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    spree_thumbnail: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=300&auto=format&fit=crop&q=80',
    metrics: {
      views_count: 9800,
      completed_views_count: 7200,
      watch_completion_rate: 0.73,
      claps_count: 2100,
      comments_count: 140,
      saves_count: 380,
      shares_count: 260,
    },
    created_at: '2026-10-02T12:00:00Z',
  },
  {
    rank: 4,
    score: 8400,
    submission_id: 'sub_004',
    spree_id: 'spree_004',
    user_id: 'usr_creator_4',
    creator_id: 'usr_creator_4',
    creator: { id: 'usr_creator_4', username: 'urban_dancer', full_name: 'Urban Dancer', avatar_url: null },
    spree_title: 'Street Cypher Session',
    username: 'Urban Dancer',
    handle: '@urban_dancer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    created_at: '2026-10-02T13:00:00Z',
  },
  {
    rank: 5,
    score: 7200,
    submission_id: 'sub_005',
    spree_id: 'spree_005',
    user_id: 'usr_creator_5',
    creator_id: 'usr_creator_5',
    creator: { id: 'usr_creator_5', username: 'zen_yogi', full_name: 'Zen Yogi', avatar_url: null },
    spree_title: 'Morning Flow Vinyasa',
    username: 'Zen Yogi',
    handle: '@zen_yogi',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    created_at: '2026-10-02T14:00:00Z',
  },
  {
    rank: 6,
    score: 6500,
    submission_id: 'sub_006',
    spree_id: 'spree_006',
    user_id: 'usr_creator_6',
    creator_id: 'usr_creator_6',
    creator: { id: 'usr_creator_6', username: 'pixel_artisan', full_name: 'Pixel Artisan', avatar_url: null },
    spree_title: '3D Cyber City Loop',
    username: 'Pixel Artisan',
    handle: '@pixel_artisan',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    created_at: '2026-10-02T15:00:00Z',
  },
  {
    rank: 7,
    score: 5900,
    submission_id: 'sub_007',
    spree_id: 'spree_007',
    user_id: 'usr_creator_7',
    creator_id: 'usr_creator_7',
    creator: { id: 'usr_creator_7', username: 'beats_by_k', full_name: 'Karan Beats', avatar_url: null },
    spree_title: 'Lofi Beat Making',
    username: 'Karan Beats',
    handle: '@beats_by_k',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    created_at: '2026-10-02T16:00:00Z',
  },
  {
    rank: 8,
    score: 5100,
    submission_id: 'sub_008',
    spree_id: 'spree_008',
    user_id: 'usr_creator_8',
    creator_id: 'usr_creator_8',
    creator: { id: 'usr_creator_8', username: 'speed_runner', full_name: 'Speed Runner', avatar_url: null },
    spree_title: 'Sub 4-Minute Mile',
    username: 'Speed Runner',
    handle: '@speed_runner',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    created_at: '2026-10-02T17:00:00Z',
  },
];

export const mockBrandCampaign: BrandCampaign = {
  id: 'campaign_tata_001',
  brand_name: 'Tata Motors',
  brand_logo_url: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=100&auto=format&fit=crop&q=80',
  campaign_title: 'Drive Your Story',
  hero_image_url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1000&auto=format&fit=crop&q=80',
  headline: 'Drive Your Story',
  description: 'Create a 30 sec spree showing how you make your journeys special with Tata.',
  reward_pool: '₹1,00,000',
  duration_days: 15,
  winners_quota: 10,
  about_brand: 'About Tata Motors: Innovation, trust and a better tomorrow. Join the movement as we celebrate creators shaping modern journeys across India.',
};

export const mockProducts: ProductItem[] = [
  {
    id: 'prod_backpack_001',
    creator_id: 'usr_travelwithme_001',
    title: 'Travel Backpack',
    description: 'Weatherproof ergonomic carry-on with quick laptop sleeve and tripod mount.',
    price_inr: 2499,
    rating: 4.8,
    image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&auto=format&fit=crop&q=80',
    is_digital: false,
    in_stock: true,
    inventory_count: 34,
    badge: 'Best Seller',
  },
  {
    id: 'prod_cap_002',
    creator_id: 'usr_travelwithme_001',
    title: 'Canvas Explorer Cap',
    description: 'Heavyweight organic cotton washed cap with embroidered compass emblem.',
    price_inr: 999,
    rating: 4.6,
    image_url: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=400&auto=format&fit=crop&q=80',
    is_digital: false,
    in_stock: true,
    inventory_count: 50,
  },
  {
    id: 'prod_journal_003',
    creator_id: 'usr_travelwithme_001',
    title: 'Field Travel Journal',
    description: 'Leather-bound grid notebook with waterproof pages and archival pen loop.',
    price_inr: 689,
    rating: 4.7,
    image_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&auto=format&fit=crop&q=80',
    is_digital: false,
    in_stock: true,
    inventory_count: 82,
  },
  {
    id: 'prod_preset_004',
    creator_id: 'usr_travelwithme_001',
    title: 'Golden Sunset Preset Pack',
    description: '12 Lightroom & mobile presets calibrated for golden hour and coastal tones.',
    price_inr: 499,
    rating: 4.5,
    image_url: 'https://images.unsplash.com/photo-1452421822248-d4c2b47f0c81?w=400&auto=format&fit=crop&q=80',
    is_digital: true,
    in_stock: true,
    inventory_count: 9999,
    badge: 'Instant Download',
  },
];

export const mockCommunityPass: CommunityPass = {
  id: 'pass_free_community',
  creator_id: 'usr_travelwithme_001',
  title: 'Creator Community Pass — Free',
  price_inr: 0,
  interval: 'month',
  description: 'Join the inner circle. Free access for verified fans.',
  benefits: [
    'Early 24h preview on all new travel sprees',
    'Exclusive behind-the-scenes moments',
    'Private member badge in chat and comments',
    'Direct voting on upcoming challenge destinations',
  ],
  is_active: true,
};

export const mockOrders: OrderRecord[] = [
  {
    id: 'ord_10821',
    product_id: 'prod_backpack_001',
    product_title: 'Travel Backpack 35L',
    product_image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=150&auto=format&fit=crop&q=80',
    price_inr: 2499,
    quantity: 1,
    total_amount_inr: 2499,
    status: 'DELIVERED',
    created_at: '2026-09-28T10:15:00Z',
  },
  {
    id: 'ord_10944',
    product_id: 'prod_cap_002',
    product_title: 'Canvas Explorer Cap',
    product_image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=150&auto=format&fit=crop&q=80',
    price_inr: 999,
    quantity: 1,
    total_amount_inr: 999,
    status: 'PROCESSING',
    created_at: '2026-10-04T15:20:00Z',
  },
];

export const mockKPIMetrics: KPIMetric[] = [
  { label: 'Views', value: '248.6K', growth_percent: 12, is_positive: true },
  { label: 'Engagement', value: '18.4K', growth_percent: 8, is_positive: true },
  { label: 'New Followers', value: '2.3K', growth_percent: 15, is_positive: true },
];

export const mockViewsTrend: TrendDataPoint[] = [
  { day: 'Mon', views: 24200, formatted_views: '24.2K' },
  { day: 'Tue', views: 28400, formatted_views: '28.4K' },
  { day: 'Wed', views: 32100, formatted_views: '32.1K' },
  { day: 'Thu', views: 30500, formatted_views: '30.5K' },
  { day: 'Fri', views: 41200, formatted_views: '41.2K' },
  { day: 'Sat', views: 48000, formatted_views: '48.0K' },
  { day: 'Sun', views: 44200, formatted_views: '44.2K' },
];

export const mockTopPerforming: TopPerformingItem[] = [
  {
    rank: 1,
    title: 'Sunset in Santorini',
    views_display: '124.8K views',
    likes_display: '8.2K likes',
    thumbnail_url: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=300&auto=format&fit=crop&q=80',
  },
  {
    rank: 2,
    title: 'Mountain Trek',
    views_display: '98.4K views',
    likes_display: '6.1K likes',
    thumbnail_url: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=300&auto=format&fit=crop&q=80',
  },
  {
    rank: 3,
    title: 'Food Diary',
    views_display: '72.3K views',
    likes_display: '4.8K likes',
    thumbnail_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=300&auto=format&fit=crop&q=80',
  },
];

export const mockWalletSummary: WalletSummary = {
  available_balance_inr: 42500,
  pending_payout_inr: 15000,
  currency: 'INR',
  upi_id: 'travelwithme@okaxis',
};

/* =====================================================================
   NOTIFICATIONS, CLUBS & STORY MOMENTS MOCK DATA
===================================================================== */
export const mockNotifications = [
  {
    id: 'notif_001',
    type: 'DROP' as const,
    title: '⚡ Exclusive Brand Drop Alert',
    message: 'Nike opened early access to the "Air Max Velocity" teaser for Club members.',
    created_at: '10m ago',
    is_read: false,
    reward_badge: 'Exclusive',
    actor_avatar: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=100',
  },
  {
    id: 'notif_002',
    type: 'BUZZER' as const,
    title: '🚀 24h Buzzer Boost Activated!',
    message: 'Your Spree "Sunset in Santorini" reached 2x reach boost. 1,420 new viewers reached!',
    created_at: '35m ago',
    is_read: false,
    reward_badge: '2x Boost',
    actor_avatar: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=100',
  },
  {
    id: 'notif_003',
    type: 'MISSION' as const,
    title: '🏆 Daily Mission Reward Claimed',
    message: 'Mission "Upload 1 Spree with sound" completed! +50 Coins added to wallet.',
    created_at: '2h ago',
    is_read: false,
    reward_badge: '+50 Coins',
  },
  {
    id: 'notif_004',
    type: 'CLAP' as const,
    title: '👏 50 Claps Received',
    message: '@foodie_riya and 49 others clapped on your Spree.',
    created_at: '4h ago',
    is_read: true,
    actor_name: 'Foodie Riya',
    actor_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100',
  },
  {
    id: 'notif_005',
    type: 'OPEN' as const,
    title: '⚔️ Competition Battle Invitation',
    message: 'You have been invited to enter "Level 2: Pro Spree Challenge" (₹50,000 Prize Pool).',
    created_at: '1d ago',
    is_read: true,
    reward_badge: '₹50,000 Pool',
  },
];

export const mockClubs = [
  {
    id: 'club_fitness',
    name: 'Fitness Hustlers',
    tagline: 'Daily transformation, workout sprees & strength battles',
    icon: '⚡',
    cover_image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600',
    members_count: 14200,
    posts_count: 840,
    category: 'Fitness',
    is_joined: true,
    active_drop: {
      title: '7-Day Core Shred Challenge',
      reward: '₹25,000 Pool',
      expires_in: '3 Days left',
    },
    pinned_thread: 'Share your 1-minute morning mobility routine!',
    top_creators: [
      { name: 'Aarav Sharma', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100' },
      { name: 'Elena Fit', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100' },
    ],
  },
  {
    id: 'club_art',
    name: 'Digital Art & Collages',
    tagline: 'Visual storytellers, 3D artists, canvas threads',
    icon: '🎨',
    cover_image: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600',
    members_count: 9800,
    posts_count: 620,
    category: 'Art & Design',
    is_joined: false,
    active_drop: {
      title: 'Cyberpunk Aesthetic Collage Thread',
      reward: 'NFT Badge + ₹15,000',
      expires_in: '5 Days left',
    },
    pinned_thread: 'Add your layer to the community evolving tapestry',
    top_creators: [
      { name: 'Maya Crafts', avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100' },
    ],
  },
  {
    id: 'club_food',
    name: 'Street Food Explorers',
    tagline: 'Hidden food stalls, secret recipes, tasting reviews',
    icon: '🍳',
    cover_image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600',
    members_count: 24500,
    posts_count: 1450,
    category: 'Food',
    is_joined: true,
    active_drop: {
      title: 'Old Delhi Midnight Chaat Spree',
      reward: 'Featured Creator Badge',
      expires_in: '1 Day left',
    },
    pinned_thread: 'Best street snack under ₹50 in your city?',
    top_creators: [
      { name: 'Foodie Riya', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100' },
    ],
  },
  {
    id: 'club_tech',
    name: 'AI & Tech Innovators',
    tagline: 'Virtual try-ons, gadgets, coding hacks & generative visuals',
    icon: '🚀',
    cover_image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600',
    members_count: 18900,
    posts_count: 910,
    category: 'Tech',
    is_joined: false,
    active_drop: {
      title: 'AI Virtual Try-On Showcase',
      reward: '₹35,000 Bounty',
      expires_in: '6 Days left',
    },
    pinned_thread: 'Show us your favorite generative UI workflow',
  },
];


export const mockMomentsBook = [
  {
    id: 'page_1',
    book_title: 'Summer Chronicles',
    page_number: 1,
    image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600',
    text: 'Page 1 • The journey began at sunrise where the waves met the golden shore.',
    date: 'June 2026',
  },
  {
    id: 'page_2',
    book_title: 'Summer Chronicles',
    page_number: 2,
    image_url: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=600',
    text: 'Page 2 • Through mountain ridges and silent pines, finding stillness in every stride.',
    date: 'July 2026',
  },
  {
    id: 'page_3',
    book_title: 'Summer Chronicles',
    page_number: 3,
    image_url: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=600',
    text: 'Page 3 • Blue domes of the Mediterranean. Every sunset told a story of its own.',
    date: 'August 2026',
  },
];

export const mockCollageThreads = [
  {
    id: 'collab_01',
    title: 'Cyberpunk Neon Dreamscape',
    creator_name: 'Maya & 8 Collaborators',
    creator_avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100',
    collaborators_count: 9,
    layers_count: 24,
    cover_url: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600',
    tags: ['cyberpunk', 'neon', 'visualart', 'community'],
  },
  {
    id: 'collab_02',
    title: 'Monsoon Chai & Rains',
    creator_name: 'Elena & 14 Spreemates',
    creator_avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100',
    collaborators_count: 15,
    layers_count: 38,
    cover_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600',
    tags: ['monsoon', 'street', 'cozy', 'story'],
  },
];
